---
title: "Untitled"
output: html_document
---
```{r}
library(ggplot2)
library(tidyverse)
library(reshape2)
```

```{r}
Main_DF<-read.csv("Initial vs freeze,thaw results.csv")

```
 
```{r}

APC_DataFrame<-Main_DF[,c(1:3,5)]


Melted_APC<-melt(APC_DataFrame,id.vars =c("Sample.ID","Sample.Type"))

for(i in 1:nrow(Melted_APC)){
  String = Melted_APC[i,4]
  str_replace(String, "<", "")
}

Melted_APC$value<-gsub("<", "", Melted_APC$value)

LevelsAPC<-APC_DataFrame$Initial.APC
LevelsAPC<-sort(LevelsAPC,decreasing = TRUE)

```

```{r}
Melted_APC$value<-as.numeric(Melted_APC$value)

ggp2 <- ggplot(Melted_APC,  aes(x =reorder(Sample.ID, -value) , y = value, color = variable, shape = variable, show.legend = F))+  
geom_line(aes(group = Sample.ID), color = "black",arrow = arrow(length=unit(0.2,"cm"), ends="last", type = "closed"))+
labs(x = "Sample ID", y = "Log CFU/g" )+
geom_point()+
theme(axis.text.x = element_text(angle = 90, size=5)) +
ggtitle("APC counts before and after freeze/thaw cycle") +
facet_wrap("Sample.Type", scales = "free_x")

ggp2

ggsave("APCFreezeThaw.jpg")
```
```{r}
Coliform_DataFrame<-Main_DF[,c(1:2,4,6)]


Melted_Coliform<-melt(Coliform_DataFrame,id.vars =c("Sample.ID","Sample.Type"))

for(i in 1:nrow(Melted_Coliform)){
  String = Melted_Coliform[i,4]
  str_replace(String, "<", "")
}

Melted_Coliform$value<-gsub("<", "", Melted_Coliform$value)

LevelsColiform<-Coliform_DataFrame$Initial.Coliform
LevelsColiform<-sort(LevelsColiform,decreasing = TRUE)


```

```{r}
Melted_Coliform$value<-as.numeric(Melted_Coliform$value)

ggp2Coliform <- ggplot(Melted_Coliform,  aes(x =reorder(Sample.ID, -value) , y = value, color = variable, shape = variable, show.legend = F))+  
geom_line(aes(group = Sample.ID), color = "black",arrow = arrow(length=unit(0.2,"cm"), ends="last", type = "closed"))+
labs(x = "Sample ID", y = "Log CFU/g" )+
geom_point()+
theme(axis.text.x = element_text(angle = 90, size=5)) +
ggtitle("Coliform counts before and after freeze/thaw cycle") +
facet_wrap("Sample.Type", scales = "free_x")

ggp2Coliform

ggsave("ColiformFreezeThaw.jpg")

```


